#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    #minnum = 0
    #maxnum = 0
    minsum = 0
    maxsum = 0
    total = 0
    
    minnum = min(arr)
    maxnum = max(arr)

    for x in arr:
        total = total + x
    
    minsum = total - maxnum
    maxsum = total - minnum
            
    print(minsum, maxsum)
            
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
