#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos = 0
    neg = 0
    zero = 0
    
    for n in arr:
        if n > 0:
            pos = pos + 1
        elif n < 0:
            neg = neg + 1
        else:
            zero = zero + 1
    
    print('%.6f' % round((pos/len(arr)), 6), end='\n')
    print('%.6f' % round((neg/len(arr)), 6), end='\n')
    print('%.6f' % round((zero/len(arr)), 6), end='\n')

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
