#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    hour = s[0:2]
    
    if "AM" in s:
        if hour == "12":
            military_time = "00" + s[2:8]
        else:
            military_time = s[0:8]
    else:
        if hour == "12":
            military_time = s[0:8]
        else:
            x = str(int(hour) + 12)
            military_time = x + s[2:8]
        
    return military_time

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
